import React, {useState, useRef} from 'react'

import Head from 'next/head'
import Image from 'next/image'
import HeadCSS from '../styles/Home.module.css'
import Header from '../component/MyHeader'

export default function Home() {
  const [open, setOpen] = useState(false);
  const node = useRef();
  const menuId = "main-menu";
  return (
    <div>
      <Head>
        <title>My! Header</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width,initial-scale=1.0, minimum-scale=1.0, user-scalable=yes" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={HeadCSS.main}>
        <Header />
      </main>

      <footer className={HeadCSS.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={HeadCSS.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}